INSERT INTO ${HiveDb}.data_quality_query_dim
VALUES
('CSG_003','bond-csg_sbscrbr_map-ingest',"select count(distinct(src_subscriber_no)) as dist_subscriber_CSG_count from bimedia.csg_subscr_map",'CSG distinct subscriber count baseline','Yes')
,('CSG_002','bond-csg_sbscrbr_map-ingest',"select count(distinct(akamai_extrn_id)) as dist_akamai_CSG_count from bimedia.csg_subscr_map",'CSG distinct AKAMAI count baseline','Yes')
,('CSG_001','bond-csg_sbscrbr_map-ingest',"select count(distinct(um_id)) as dist_UM_CSG_count from bimedia.csg_subscr_map",'CSG distinct UM count baseline','Yes')
,('OHD_SUB_CSG_002','populate_bond_content_views_dtl', "select count(distinct(ohd_tmp.akamai_id)) as count_dist_AKAM_missing_CSG_SUB from (Select ohd.akamai_id from bimedia.omniture_hit_data ohd where ohd.cust_type_cd = 'DTC' and concat(ohd.year,ohd.month) = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))) ohd_tmp left join (select * from (select * from bimedia.subscriber_dim sd) sd_tmp inner join (select * from bimedia.csg_subscr_map csg) csg_tmp on cast(sd_tmp.subscriber_id  as string) = csg_tmp.src_subscriber_no) csg_subsc on ohd_tmp.akamai_id = csg_subsc.akamai_extrn_id where ohd_tmp.akamai_id is not null and ohd_tmp.akamai_id != 'None' and csg_subsc.akamai_extrn_id is null",'Count of umapped AKAMAI users between OHD, CSG Subscriber Map, and Subscriber Dim','Yes')
,('OHD_SUB_CSG_001','populate_bond_content_views_dtl', "select count(distinct(ohd_tmp.um_id)) as count_dist_UM_missing_CSG_SUB from (Select ohd.um_id from bimedia.omniture_hit_data ohd where ohd.cust_type_cd ='DTC'and concat(ohd.year,ohd.month) = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))) ohd_tmp left join (select * from (select * from bimedia.subscriber_dim sd) sd_tmp inner join (select * from bimedia.csg_subscr_map csg) csg_tmp on cast(sd_tmp.subscriber_id  as string) = csg_tmp.src_subscriber_no) csg_subsc on ohd_tmp.um_id = csg_subsc.um_id where ohd_tmp.um_id is not null and ohd_tmp.um_id != 'None' and csg_subsc.um_id is null",'Count of umapped UM users between OHD, CSG Subscriber Map, and Subscriber Dim','Yes')
,('SUB_001','bond_subscriber_dim-ingest',"select count (distinct(subscriber_id) ) as dist_subscriber_dim_count from bimedia.subscriber_dim",'Subscriber dimension baseline','Yes')
,('OHD_002','bond_populate_bond_content_views_smry',"SELECT count(DISTINCT(akamai_id)) as dist_akamai_OHD_count from bimedia.omniture_hit_data where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)",'OHD distinct akamai count baseline','Yes')
,('OHD_001','bond_populate_bond_content_views_smry',"SELECT count(DISTINCT(um_id)) as dist_UM_OHD_count from bimedia.omniture_hit_data where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)",'OHD distinct UM count baseline','Yes')

,('OHD_0031','bond_populate_bond_content_views_smry',"SELECT count(distinct(content_package_id)) as dist_PKid_OHD_count from bimedia.omniture_hit_data where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)",'OHD distinct PKid count baseline','Yes')
,('OHD_0041','bond_populate_bond_content_views_smry',"SELECT count(distinct(content_id)) as dist_Contentid_OHD_count from bimedia.omniture_hit_data where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)",'OHD distinct PKid count baseline','Yes')
,('CCM_0031','bond_populate_bond_content_views_smry',"SELECT count(distinct(content_package_id)) as dist_PKid_CCM_count from bimedia.crave_content_master",'CCM distinct Content PackageID count baseline','Yes')
,('CCM_0041','bond_populate_bond_content_views_smry',"SELECT count(distinct(content_id)) as dist_Contentid_CCM_count from bimedia.crave_content_master",'CCM distinct ContentID count baseline','Yes')

,('OHD_CCM_0031','bond_populate_bond_content_views_smry',"select count(distinct (ohd.content_package_id)) as dist_count_OHD_PKid_Unmapped_CCM from bimedia.omniture_hit_data ohd left join (SELECT distinct(content_package_id) as ccm_pk from bimedia.crave_content_master) ccm_tmp on ohd.content_package_id= ccm_tmp.ccm_pk where ccm_tmp.ccm_pk is null and concat(ohd.year,ohd.month) = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))",'OHD distinct PKid unmapped to CCM','Yes')
,('OHD_CCM_0041','bond_populate_bond_content_views_smry',"select count(distinct (ohd.content_id)) as dist_count_OHD_Contid_Unmapped_CCM from bimedia.omniture_hit_data ohd left join (SELECT distinct(content_id) as ccm_Cont_id from bimedia.crave_content_master) ccm_tmp on ohd.content_id = ccm_tmp.ccm_Cont_id where ccm_tmp.ccm_Cont_id is null and concat(ohd.year,ohd.month) = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))",'OHD distinct Contid unmapped to CCM','Yes')

,('OHD_0033','bond_populate_bond_content_views_smry',"SELECT count(DISTINCT(ohd.content_package_id)) as OHD_Unmapped_PKID_CCM from bimedia.omniture_hit_data ohd LEFT JOIN bimedia.crave_content_master ccm on cast(ohd.content_package_id as string) = cast(ccm.content_package_id as STRING) where ccm.content_package_id is null and (ohd.year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and ohd.month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))",'Count of umapped Content PK ID between OHD and CCM','Yes')
,('FIB_0033','bond_populate_bond_content_views_smry',"Select count(*) as Fibe_Unmapped_ID_CMS from (select distinct src_content_id as Fibe_ID,brand_cd,year,month from bimedia.fibe_video_consumption where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0) ) FVC left join (select distinct cphd_id,regexp_extract(cphd_id, '[0-9]+', 0) as cphd_check, tcs_master_id from bimedia.cms_master where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)) CMS on FVC.Fibe_ID = CMS.tcs_master_id where cphd_id is  NULL",'Count of umapped FIBE ID between FIBE and CMS','Yes')
,('ALT_0033','bond_populate_bond_content_views_smry', "Select count(*) as ALIANT_Unmapped_ID_CMS  from (select distinct src_content_id as aliant_ID,brand_cd,year,month from bimedia.aliant_video_consumption where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)) AVC left join (select distinct cphd_id,regexp_extract(cphd_id, '[0-9]+', 0) as cphd_check,tcs_master_id from bimedia.cms_master where year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)) CMS on AVC.aliant_ID = CMS.tcs_master_id where cphd_id is NULL",'Count of umapped ALIANT ID between ALIANT and CMS','Yes')
,('TLS_0033','bond_populate_bond_content_views_smry', "WITH telus_to_crave as ( select distinct tvc1.src_content_id,nvl(cm1.content_id, cm1.content_id) content_id_f from bimedia.telus_video_consumption tvc1 left join bimedia.crave_content_master cm1 on cast(tvc1.src_content_id as string) = cast (cm1.content_package_id as string) left join bimedia.crave_content_master cm2 on substring(cast(tvc1.src_content_id as string),1,6) = cast(cm2.content_package_id as String) where tvc1.yyyymm = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0)) and src_content_id is not null) select count(*) as TELUS_Unmapped_PKID_CMS from telus_to_crave where content_id_f is NULL",'Count of umapped Content PK ID between TELUS and CCM','Yes')
,('CMS_0033','bond_populate_bond_content_views_smry', "SELECT count(DISTINCT(cms.cphd_id)) as CMS_Unmapped_PKID_CCM from bimedia.cms_master cms LEFT JOIN bimedia.crave_content_master ccm on cast(cms.cphd_id as string) = cast(ccm.content_package_id as STRING) where  ccm.content_package_id is null  and (cms.year = year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)) and cms.month = lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))",'Count of umapped Content PK ID between CMS and CCM','Yes')
,('EST_0033','bond_populate_bond_content_views_smry', "WITH eastlink_to_crave as (select distinct evc.provider_asset_id  ,nvl(cm1.content_id, cm2.content_id) content_id_f  ,nvl(cm1.brand_cd, cm2.brand_cd) brand_cd_f  from bimedia.eastlink_video_consumption evc    left join bimedia.crave_content_master cm1  on cast(evc.provider_asset_id  as string) = cast (cm1.content_package_id as string)left join bimedia.crave_content_master cm2 on substring(cast(evc.provider_asset_id as string),1,6) = cast(cm2.content_package_id as String) where evc.yyyymm = concat(year(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),lpad(month(add_months(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),-1)),2,0))) select count(*) as EASTLINK_Unmapped_PKID_CCM from eastlink_to_crave where content_id_f is NULL",'Count of umapped Content PK ID between EASTLINK and CCM','Yes')
;
